### ISSUE TITLE
一些使用上的问题

### ISSUE THREAD

**Issue by DOVIS4415** [AIGODLIKE/Bbrush#2]
使用版本：blender stable 4.1.1

1.Ctrl Shift+左键单击网格报错
![微信截图_20240517154643](https://github.com/AIGODLIKE/Bbrush/assets/65146571/8f77aff3-4170-4af5-90c0-4ae326007e65)

2.Ctrl Shift+左键框选空白处报错
![微信截图_202405171550566](https://github.com/AIGODLIKE/Bbrush/assets/65146571/d6452119-25c8-4e29-a634-38293c115ab4)

3.Shift+F覆盖了Blender快捷键变成了只调整平滑笔刷的强度（调整平滑笔刷强度的功能也很好用，但也许可以给用户决定另外的快捷键）

4.BBrush设定的快捷键更改了之后，下一次进入雕刻模式会强制新加一次默认快捷键（也会强制还原blender右键松开的sculpt_context_menu）

5.左键单击空白处就会一直旋转视图（zb为按住左键旋转，希望加个快捷键选项可以设置关闭）

6.左键旋转视图与3D View Tool: Sculpt, Mesh Filter, 网格滤镜有冲突（左键拖拽起作用）

**Comment by xmx-emm** [comment]
3的话已经修复了[v1.2.4](https://github.com/AIGODLIKE/Bbrush/releases/tag/v1.2.4)

**Comment by xmx-emm** [comment]
其它的我看看

**Comment by xmx-emm** [comment]
用的什么版本的

**Comment by DOVIS4415** [comment]
> 3的话已经修复了[v1.2.4](https://github.com/AIGODLIKE/Bbrush/releases/tag/v1.2.4)

收到 辛苦大佬！

**Comment by xmx-emm** [comment]
1 2 5 已修复
4是因为每次退出模式的时需要恢复快捷键,会把所有符合规则的快捷键都复位,避免快捷键错误
6的话暂时没有解决方法,笔刷操作的优先级高于插件,可以使用右键代替左键旋转

**Comment by xmx-emm** [comment]
差不多修完了[v1.2.5](https://github.com/AIGODLIKE/Bbrush/releases/tag/v1.2.5)
还有其它问题的话再提issues

**Comment by DOVIS4415** [comment]
感谢大佬
