### ISSUE TITLE
左键单击模型

### ISSUE THREAD

**Issue by DOVIS4415** [AIGODLIKE/Bbrush#4]
使用版本：blender stable 4.1.1
大佬，还有一个小问题，如果左键不小心单击了模型，就会和按住左键雕刻一样，右键无法取消，只能左键确认，再Ctrl+Z撤回

**Comment by xmx-emm** [comment]
zbrush怎么处理的啊

**Comment by xmx-emm** [comment]
[v1.2.6](https://github.com/AIGODLIKE/Bbrush/releases/tag/v1.2.6)
这个问题好了

**Comment by xmx-emm** [comment]
还有啥再提

**Comment by xmx-emm** [comment]
emm github的消息不太常看
还有啥问题可以直接进频道问
回复会快些

点击链接加入QQ频道【萌新聚集地】：https://pd.qq.com/s/2wl9igdj4

**Comment by DOVIS4415** [comment]
> emm github的消息不太常看 还有啥问题可以直接进频道问 回复会快些
> 
> 点击链接加入QQ频道【萌新聚集地】：https://pd.qq.com/s/2wl9igdj4



> emm github的消息不太常看 还有啥问题可以直接进频道问 回复会快些
> 
> 点击链接加入QQ频道【萌新聚集地】：https://pd.qq.com/s/2wl9igdj4

好嘞好嘞 大佬 已经进了
